# Generated by Django 6.0.2 on 2026-02-20 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='We will contact you at this email regarding your submission.', max_length=254, unique=True)),
                ('bio', models.TextField(help_text='Please provide a brief summary about the author, awards, publications, and mentions.')),
            ],
        ),
    ]
