# Generated by Django 6.0.2 on 2026-02-22 19:49

import authors.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(help_text='Please provide a brief summary about yourself, including any awards, publications, and mentions.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='First name (letters and dashes only).', max_length=50, validators=[django.core.validators.MinLengthValidator(2), authors.models.validate_letters_and_dashes]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Last name (letters and dashes only).', max_length=50, validators=[django.core.validators.MinLengthValidator(2), authors.models.validate_letters_and_dashes]),
        ),
    ]
