# Generated by Django 6.0.2 on 2026-02-20 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField(help_text='Please provide a short synopsis including story description and targeted audience.')),
                ('script_sample', models.TextField(help_text='Please provide a part of the actual book script (min 10000 characters).', validators=[django.core.validators.MinLengthValidator(10000)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('review', 'Under Review'), ('accepted', 'Accepted for Publication'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='authors.author')),
                ('genres', models.ManyToManyField(related_name='submissions', to='submissions.genre')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
