# Generated by Django 6.0.2 on 2026-02-22 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='script_sample',
            field=models.TextField(help_text='Please provide a part of the actual book script (min 1000 characters).', validators=[django.core.validators.MinLengthValidator(1000)]),
        ),
    ]
