# Generated by Django 6.0.2 on 2026-02-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_options_alter_author_bio_and_more'),
        ('submissions', '0002_alter_submission_script_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(help_text='Please select an author or add a new author by visiting Main/Top Menu -> Authors.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='genres',
            field=models.ManyToManyField(help_text='Please select applicable genres or add a new genre by visiting Main/Top Menu -> Genres.', related_name='submissions', to='submissions.genre'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='synopsis',
            field=models.TextField(help_text='Please provide a short synopsis of the story.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(help_text='Please enter the title of the submission.', max_length=200),
        ),
    ]
